# Accessibility Configuration
# ============================================

# WCAG Compliance
WCAG_COMPLIANCE:
  level: "AA"
  version: "2.1"
  guidelines:
    - perceivable
    - operable
    - understandable
    - robust

# Color Contrast
COLOR_CONTRAST:
  normal_text: 4.5:1
  large_text: 3:1
  ui_components: 3:1
  focus_indicators: 3:1

# Keyboard Navigation
KEYBOARD_NAVIGATION:
  tab_order: true
  focus_management: true
  skip_links: true
  keyboard_shortcuts: true
  focus_traps: true

# Screen Reader Support
SCREEN_READER_SUPPORT:
  semantic_html: true
  aria_labels: true
  aria_descriptions: true
  aria_live_regions: true
  alt_text: true

# Visual Accessibility
VISUAL_ACCESSIBILITY:
  font_scaling: true
  high_contrast_mode: true
  reduced_motion: true
  color_blind_support: true
  text_resize: true

# Motor Accessibility
MOTOR_ACCESSIBILITY:
  large_touch_targets: true
  gesture_alternatives: true
  voice_control: true
  switch_navigation: true
  timeout_extensions: true

# Cognitive Accessibility
COGNITIVE_ACCESSIBILITY:
  clear_language: true
  consistent_navigation: true
  error_prevention: true
  help_text: true
  progress_indicators: true

# Testing
ACCESSIBILITY_TESTING:
  automated_testing: true
  manual_testing: true
  screen_reader_testing: true
  keyboard_testing: true
  color_contrast_testing: true

# Tools Integration
TOOLS_INTEGRATION:
  axe_core: true
  lighthouse: true
  wave: true
  nvda: true
  jaws: true
  voiceover: true

# Documentation
ACCESSIBILITY_DOCUMENTATION:
  accessibility_statement: true
  keyboard_shortcuts: true
  screen_reader_guide: true
  contact_information: true
  feedback_mechanism: true
