# Backup Configuration
# ============================================

# Backup Schedule
BACKUP_SCHEDULE:
  full_backup: "0 2 * * *"  # Daily at 2 AM
  incremental_backup: "0 */6 * * *"  # Every 6 hours
  cleanup_old_backups: "0 3 * * 0"  # Weekly cleanup

# Backup Retention
BACKUP_RETENTION:
  daily_backups: 7 days
  weekly_backups: 4 weeks
  monthly_backups: 12 months
  yearly_backups: 7 years

# Tables to Backup
BACKUP_TABLES:
  critical:
    - profiles
    - products
    - categories
    - orders
    - order_items
    - stores
    - product_images
    - reviews
    - messages
    - notifications
  
  optional:
    - cart_items
    - search_history
    - user_preferences
    - analytics_events

# Backup Storage
BACKUP_STORAGE:
  primary: "supabase_storage"
  secondary: "external_storage"
  encryption: true
  compression: true

# Backup Verification
BACKUP_VERIFICATION:
  checksum_verification: true
  restore_testing: true
  integrity_check: true
  performance_testing: true

# Alert Configuration
BACKUP_ALERTS:
  failure_notifications: true
  success_notifications: false
  storage_quota_alerts: true
  performance_alerts: true

# Recovery Procedures
RECOVERY_PROCEDURES:
  point_in_time_recovery: true
  selective_restore: true
  cross_region_restore: true
  disaster_recovery: true
