# Culture Configuration
# ============================================

# Core Values
CORE_VALUES:
  integrity: true
  innovation: true
  collaboration: true
  customer_focus: true
  excellence: true

# Cultural Elements
CULTURAL_ELEMENTS:
  mission_statement: true
  vision_statement: true
  values_statement: true
  code_of_conduct: true
  cultural_norms: true

# Diversity and Inclusion
DIVERSITY_INCLUSION:
  diversity_policies: true
  inclusion_initiatives: true
  equal_opportunity: true
  cultural_sensitivity: true
  bias_training: true

# Work Environment
WORK_ENVIRONMENT:
  flexible_work: true
  remote_work: true
  work_life_balance: true
  wellness_programs: true
  professional_development: true

# Communication Culture
COMMUNICATION_CULTURE:
  open_communication: true
  feedback_culture: true
  transparency: true
  respect: true
  active_listening: true

# Innovation Culture
INNOVATION_CULTURE:
  creativity_encouragement: true
  experimentation: true
  learning_from_failure: true
  continuous_improvement: true
  knowledge_sharing: true

# Performance Culture
PERFORMANCE_CULTURE:
  high_performance: true
  accountability: true
  recognition: true
  development: true
  results_orientation: true

# Cultural Metrics
CULTURAL_METRICS:
  employee_satisfaction: true
  engagement_scores: true
  retention_rates: true
  diversity_metrics: true
  cultural_assessments: true

# Cultural Development
CULTURAL_DEVELOPMENT:
  cultural_training: true
  team_building: true
  cultural_events: true
  recognition_programs: true
  cultural_communication: true
