# Governance Configuration
# ============================================

# Data Governance
DATA_GOVERNANCE:
  data_classification: true
  data_ownership: true
  data_quality: true
  data_lineage: true
  data_privacy: true

# Security Governance
SECURITY_GOVERNANCE:
  security_policies: true
  access_control: true
  risk_management: true
  incident_response: true
  compliance_monitoring: true

# IT Governance
IT_GOVERNANCE:
  architecture_review: true
  technology_standards: true
  change_management: true
  project_governance: true
  resource_management: true

# Business Governance
BUSINESS_GOVERNANCE:
  business_rules: true
  process_governance: true
  decision_making: true
  accountability: true
  transparency: true

# Compliance Governance
COMPLIANCE_GOVERNANCE:
  regulatory_compliance: true
  policy_management: true
  audit_management: true
  risk_assessment: true
  control_monitoring: true

# Quality Governance
QUALITY_GOVERNANCE:
  quality_standards: true
  quality_metrics: true
  quality_reviews: true
  continuous_improvement: true
  best_practices: true

# Performance Governance
PERFORMANCE_GOVERNANCE:
  performance_standards: true
  performance_metrics: true
  performance_reviews: true
  optimization: true
  benchmarking: true

# Change Governance
CHANGE_GOVERNANCE:
  change_approval: true
  change_documentation: true
  change_communication: true
  change_validation: true
  change_rollback: true

# Stakeholder Governance
STAKEHOLDER_GOVERNANCE:
  stakeholder_engagement: true
  communication_management: true
  expectation_management: true
  feedback_management: true
  relationship_management: true
