# Integration Configuration
# ============================================

# Payment Gateways
PAYMENT_GATEWAYS:
  primary: "stripe"
  secondary: "paypal"
  local:
    - "banco_nacional"
    - "banco_itau"
    - "banco_continental"
  crypto:
    - "bitcoin"
    - "ethereum"
    - "usdt"

# Shipping Providers
SHIPPING_PROVIDERS:
  local:
    - "correo_paraguayo"
    - "oca"
    - "dhl"
    - "fedex"
  regional:
    - "mercosur_logistics"
    - "south_american_shipping"

# Email Services
EMAIL_SERVICES:
  primary: "sendgrid"
  secondary: "mailgun"
  transactional: "supabase_auth"
  marketing: "mailchimp"

# SMS Services
SMS_SERVICES:
  primary: "twilio"
  local: "tigo"
  fallback: "claro"

# Push Notifications
PUSH_NOTIFICATIONS:
  service: "firebase"
  web_push: true
  mobile_push: true
  desktop_push: true

# Analytics Services
ANALYTICS_SERVICES:
  primary: "google_analytics"
  secondary: "mixpanel"
  ecommerce: "google_analytics_ecommerce"
  user_behavior: "hotjar"

# Social Media
SOCIAL_MEDIA:
  facebook: true
  instagram: true
  twitter: true
  linkedin: true
  tiktok: true
  youtube: true

# Third-party APIs
THIRD_PARTY_APIS:
  maps: "google_maps"
  weather: "openweathermap"
  currency: "fixer_io"
  news: "newsapi"
  reviews: "trustpilot"

# Webhooks
WEBHOOKS:
  payment_confirmations: true
  order_status_updates: true
  inventory_changes: true
  user_registrations: true
  product_reviews: true

# API Rate Limits
API_RATE_LIMITS:
  stripe: "1000/hour"
  paypal: "500/hour"
  sendgrid: "10000/day"
  twilio: "1000/day"
  google_maps: "1000/day"

# Error Handling
INTEGRATION_ERROR_HANDLING:
  retry_logic: true
  circuit_breaker: true
  fallback_services: true
  error_notifications: true
  logging: true

# Security
INTEGRATION_SECURITY:
  api_key_management: true
  webhook_verification: true
  ssl_enforcement: true
  rate_limiting: true
  ip_whitelisting: true
