# Kubernetes Deployment Configuration
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mercadito-online-py
  labels:
    app: mercadito-online-py
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mercadito-online-py
  template:
    metadata:
      labels:
        app: mercadito-online-py
    spec:
      containers:
      - name: app
        image: mercadito-online-py:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_SUPABASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: supabase-url
        - name: NEXT_PUBLIC_SUPABASE_ANON_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: supabase-anon-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: mercadito-online-py-service
spec:
  selector:
    app: mercadito-online-py
  ports:
  - port: 80
    targetPort: 3000
  type: LoadBalancer

---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  supabase-url: <base64-encoded-url>
  supabase-anon-key: <base64-encoded-key>
