# Leadership Configuration
# ============================================

# Leadership Styles
LEADERSHIP_STYLES:
  transformational: true
  servant_leadership: true
  adaptive_leadership: true
  collaborative_leadership: true
  strategic_leadership: true

# Leadership Development
LEADERSHIP_DEVELOPMENT:
  leadership_training: true
  mentoring_programs: true
  coaching: true
  leadership_assessment: true
  succession_planning: true

# Leadership Competencies
LEADERSHIP_COMPETENCIES:
  strategic_thinking: true
  decision_making: true
  communication: true
  emotional_intelligence: true
  change_management: true

# Team Leadership
TEAM_LEADERSHIP:
  team_building: true
  conflict_resolution: true
  performance_management: true
  motivation: true
  delegation: true

# Organizational Leadership
ORGANIZATIONAL_LEADERSHIP:
  vision_setting: true
  culture_building: true
  innovation_leadership: true
  stakeholder_management: true
  organizational_development: true

# Leadership Metrics
LEADERSHIP_METRICS:
  team_performance: true
  employee_satisfaction: true
  retention_rates: true
  innovation_metrics: true
  business_results: true

# Leadership Challenges
LEADERSHIP_CHALLENGES:
  remote_leadership: true
  digital_transformation: true
  diversity_inclusion: true
  sustainability: true
  crisis_leadership: true

# Leadership Support
LEADERSHIP_SUPPORT:
  executive_coaching: true
  peer_networking: true
  leadership_resources: true
  best_practices: true
  continuous_learning: true

# Leadership Culture
LEADERSHIP_CULTURE:
  leadership_values: true
  ethical_leadership: true
  inclusive_leadership: true
  collaborative_culture: true
  learning_organization: true
