# Learning Management Configuration
# ============================================

# Learning Strategy
LEARNING_STRATEGY:
  learning_planning: true
  learning_goals: true
  learning_standards: true
  learning_metrics: true
  learning_improvement: true

# Learning Management
LEARNING_MANAGEMENT:
  learning_planning: true
  learning_delivery: true
  learning_assessment: true
  learning_evaluation: true
  learning_improvement: true

# Learning Systems
LEARNING_SYSTEMS:
  lms_platforms: true
  content_management: true
  assessment_systems: true
  collaboration_platforms: true
  analytics_platforms: true

# Learning Analytics
LEARNING_ANALYTICS:
  learning_metrics: true
  performance_analysis: true
  trend_analysis: true
  impact_analysis: true
  predictive_analytics: true

# Learning Technology
LEARNING_TECHNOLOGY:
  learning_platforms: true
  content_creation: true
  assessment_tools: true
  analytics_platforms: true
  automation_tools: true

# Learning Culture
LEARNING_CULTURE:
  learning_mindset: true
  continuous_learning: true
  learning_innovation: true
  learning_collaboration: true
  learning_leadership: true

# Learning Training
LEARNING_TRAINING:
  learning_awareness: true
  learning_skills: true
  learning_tools: true
  learning_methods: true
  learning_best_practices: true

# Learning Governance
LEARNING_GOVERNANCE:
  learning_policies: true
  learning_procedures: true
  learning_standards: true
  learning_compliance: true
  learning_oversight: true

# Learning Operations
LEARNING_OPERATIONS:
  learning_processes: true
  learning_workflows: true
  learning_governance: true
  learning_support: true
  learning_administration: true
