# Marketing Configuration
# ============================================

# Marketing Strategy
MARKETING_STRATEGY:
  brand_strategy: true
  market_positioning: true
  target_audience: true
  value_proposition: true
  competitive_advantage: true

# Digital Marketing
DIGITAL_MARKETING:
  seo: true
  sem: true
  social_media: true
  content_marketing: true
  email_marketing: true

# Content Marketing
CONTENT_MARKETING:
  content_strategy: true
  content_creation: true
  content_distribution: true
  content_optimization: true
  content_analytics: true

# Social Media Marketing
SOCIAL_MEDIA_MARKETING:
  facebook: true
  instagram: true
  twitter: true
  linkedin: true
  tiktok: true
  youtube: true

# Email Marketing
EMAIL_MARKETING:
  email_campaigns: true
  email_automation: true
  email_segmentation: true
  email_analytics: true
  email_optimization: true

# Performance Marketing
PERFORMANCE_MARKETING:
  paid_advertising: true
  affiliate_marketing: true
  influencer_marketing: true
  retargeting: true
  conversion_optimization: true

# Marketing Analytics
MARKETING_ANALYTICS:
  campaign_tracking: true
  roi_measurement: true
  attribution_modeling: true
  customer_analytics: true
  marketing_automation: true

# Marketing Technology
MARKETING_TECHNOLOGY:
  crm_systems: true
  marketing_automation: true
  analytics_platforms: true
  social_media_tools: true
  email_platforms: true

# Marketing Operations
MARKETING_OPERATIONS:
  campaign_management: true
  lead_management: true
  customer_journey: true
  marketing_workflows: true
  marketing_governance: true
