# Operations Management Configuration
# ============================================

# Operations Strategy
OPERATIONS_STRATEGY:
  operations_planning: true
  operations_goals: true
  operations_standards: true
  operations_metrics: true
  operations_improvement: true

# Operations Management
OPERATIONS_MANAGEMENT:
  operations_planning: true
  operations_execution: true
  operations_monitoring: true
  operations_evaluation: true
  operations_improvement: true

# Operations Systems
OPERATIONS_SYSTEMS:
  operations_platforms: true
  monitoring_systems: true
  automation_systems: true
  reporting_systems: true
  analytics_platforms: true

# Operations Analytics
OPERATIONS_ANALYTICS:
  operations_metrics: true
  performance_analysis: true
  trend_analysis: true
  impact_analysis: true
  predictive_analytics: true

# Operations Technology
OPERATIONS_TECHNOLOGY:
  operations_tools: true
  monitoring_tools: true
  automation_tools: true
  analytics_platforms: true
  integration_platforms: true

# Operations Culture
OPERATIONS_CULTURE:
  operations_mindset: true
  efficiency_focus: true
  operations_innovation: true
  operations_collaboration: true
  operations_leadership: true

# Operations Training
OPERATIONS_TRAINING:
  operations_awareness: true
  operations_skills: true
  operations_tools: true
  operations_methods: true
  operations_best_practices: true

# Operations Governance
OPERATIONS_GOVERNANCE:
  operations_policies: true
  operations_procedures: true
  operations_standards: true
  operations_compliance: true
  operations_oversight: true

# Operations Operations
OPERATIONS_OPERATIONS:
  operations_processes: true
  operations_workflows: true
  operations_governance: true
  operations_support: true
  operations_administration: true
