# Quality Management Configuration
# ============================================

# Quality Strategy
QUALITY_STRATEGY:
  quality_planning: true
  quality_goals: true
  quality_standards: true
  quality_metrics: true
  quality_improvement: true

# Quality Control
QUALITY_CONTROL:
  inspection: true
  testing: true
  sampling: true
  defect_analysis: true
  corrective_action: true

# Quality Assurance
QUALITY_ASSURANCE:
  process_audits: true
  system_audits: true
  compliance_audits: true
  supplier_audits: true
  internal_audits: true

# Quality Management System
QUALITY_MANAGEMENT_SYSTEM:
  qms_implementation: true
  qms_documentation: true
  qms_monitoring: true
  qms_improvement: true
  qms_certification: true

# Quality Analytics
QUALITY_ANALYTICS:
  quality_metrics: true
  performance_analysis: true
  trend_analysis: true
  root_cause_analysis: true
  predictive_analytics: true

# Quality Technology
QUALITY_TECHNOLOGY:
  qms_systems: true
  testing_equipment: true
  measurement_systems: true
  analytics_platforms: true
  automation_tools: true

# Quality Standards
QUALITY_STANDARDS:
  iso_9001: true
  iso_14001: true
  iso_45001: true
  industry_standards: true
  customer_standards: true

# Quality Training
QUALITY_TRAINING:
  quality_awareness: true
  quality_tools: true
  quality_methods: true
  quality_standards: true
  continuous_improvement: true

# Quality Operations
QUALITY_OPERATIONS:
  quality_processes: true
  quality_workflows: true
  quality_governance: true
  quality_support: true
  quality_administration: true
