# Security Management Configuration
# ============================================

# Security Strategy
SECURITY_STRATEGY:
  security_planning: true
  security_goals: true
  security_standards: true
  security_metrics: true
  security_improvement: true

# Physical Security
PHYSICAL_SECURITY:
  access_control: true
  surveillance: true
  perimeter_security: true
  security_guards: true
  security_systems: true

# Information Security
INFORMATION_SECURITY:
  data_protection: true
  network_security: true
  application_security: true
  endpoint_security: true
  cloud_security: true

# Cybersecurity
CYBERSECURITY:
  threat_detection: true
  incident_response: true
  vulnerability_management: true
  security_monitoring: true
  security_analytics: true

# Security Operations
SECURITY_OPERATIONS:
  security_monitoring: true
  incident_response: true
  threat_hunting: true
  security_analytics: true
  security_reporting: true

# Security Technology
SECURITY_TECHNOLOGY:
  security_systems: true
  monitoring_tools: true
  analytics_platforms: true
  automation_tools: true
  integration_platforms: true

# Security Compliance
SECURITY_COMPLIANCE:
  regulatory_compliance: true
  industry_standards: true
  security_policies: true
  compliance_monitoring: true
  compliance_reporting: true

# Security Training
SECURITY_TRAINING:
  security_awareness: true
  security_skills: true
  incident_response: true
  security_tools: true
  security_best_practices: true

# Security Governance
SECURITY_GOVERNANCE:
  security_policies: true
  security_procedures: true
  security_governance: true
  security_oversight: true
  security_audit: true
