# Security Configuration
# ============================================

# Authentication
AUTHENTICATION:
  provider: "supabase"
  session_timeout: "24h"
  refresh_token_expiry: "30d"
  password_policy:
    min_length: 8
    require_uppercase: true
    require_lowercase: true
    require_numbers: true
    require_symbols: true
  two_factor_auth: true
  social_login:
    google: true
    facebook: true
    github: false

# Authorization
AUTHORIZATION:
  role_based_access: true
  permissions:
    admin: ["*"]
    seller: ["products:crud", "orders:read", "analytics:read"]
    buyer: ["products:read", "orders:crud", "cart:crud"]
  resource_protection: true
  api_rate_limiting: true

# Data Protection
DATA_PROTECTION:
  encryption_at_rest: true
  encryption_in_transit: true
  data_anonymization: true
  pii_protection: true
  gdpr_compliance: true
  data_retention_policy: true

# Input Validation
INPUT_VALIDATION:
  sql_injection_protection: true
  xss_protection: true
  csrf_protection: true
  file_upload_validation: true
  input_sanitization: true
  schema_validation: true

# Security Headers
SECURITY_HEADERS:
  content_security_policy: true
  x_frame_options: "DENY"
  x_content_type_options: "nosniff"
  referrer_policy: "strict-origin-when-cross-origin"
  strict_transport_security: true
  permissions_policy: true

# Monitoring
SECURITY_MONITORING:
  intrusion_detection: true
  anomaly_detection: true
  failed_login_monitoring: true
  suspicious_activity: true
  security_incident_response: true

# Vulnerability Management
VULNERABILITY_MANAGEMENT:
  dependency_scanning: true
  code_analysis: true
  penetration_testing: true
  security_audits: true
  vulnerability_patching: true

# Compliance
COMPLIANCE:
  gdpr: true
  ccpa: true
  pci_dss: true
  iso_27001: true
  soc_2: true

# Incident Response
INCIDENT_RESPONSE:
  automated_response: true
  escalation_procedures: true
  communication_plan: true
  recovery_procedures: true
  post_incident_review: true
