/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class', // Habilitar dark mode con clase
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  safelist: [
    // Botones principales
    'bg-blue-600',
    'hover:bg-blue-700',
    'bg-red-500',
    'hover:bg-red-600',
    'bg-green-500',
    'bg-black',
    'hover:bg-gray-800',
    'bg-white',
    'hover:bg-white/90',
    'bg-gray-400',
    'text-white',
    'text-cyan-700',
    'hover:bg-gray-50',
    'hover:bg-gray-100',
    'border-white/70',
    'hover:bg-white/10',
    // Estados y transiciones
    'transition-colors',
    'transition-all',
    'duration-200',
    'active:scale-95',
    'hover:shadow-md',
    // Focus states
    'focus:outline-none',
    'focus:ring-2',
    'focus:ring-offset-2',
    'focus:ring-blue-500',
    'focus:ring-gray-500',
    'focus:ring-red-500',
    'focus:ring-white/70',
    // Disabled states
    'disabled:opacity-50',
    'disabled:cursor-not-allowed',
    // Hero slider - clases literales para controles y CTA
    'relative',
    'w-full',
    'overflow-hidden',
    'absolute',
    'left-3',
    'right-3',
    'top-1/2',
    '-translate-y-1/2',
    'z-50',
    'inline-flex',
    'items-center',
    'justify-center',
    'rounded-full',
    'rounded-lg',
    'px-3',
    'px-5',
    'py-2',
    'py-2.5',
    'bg-white',
    'text-gray-900',
    'shadow',
    'hover:bg-gray-100',
    'bg-primary',
    'text-white',
    'hover:bg-primary/90',
    'mt-4',
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}

