# Testing Configuration
# ============================================

# Test Types
TEST_TYPES:
  unit_tests: true
  integration_tests: true
  e2e_tests: true
  performance_tests: true
  accessibility_tests: true
  security_tests: true

# Test Coverage
TEST_COVERAGE:
  minimum_coverage: 80%
  target_coverage: 90%
  critical_paths: 95%
  exclude_patterns:
    - "**/*.test.ts"
    - "**/*.spec.ts"
    - "**/node_modules/**"
    - "**/.next/**"
    - "**/coverage/**"

# E2E Testing
E2E_TESTING:
  browser_support:
    - chrome
    - firefox
    - safari
    - edge
  device_support:
    - desktop
    - tablet
    - mobile
  test_scenarios:
    - user_registration
    - user_login
    - product_browsing
    - product_search
    - add_to_cart
    - checkout_process
    - seller_registration
    - product_creation
    - order_management
    - chat_functionality

# Performance Testing
PERFORMANCE_TESTING:
  lighthouse_thresholds:
    performance: 90
    accessibility: 90
    best_practices: 90
    seo: 90
  load_testing:
    concurrent_users: 100
    duration: "5m"
    ramp_up: "1m"
  stress_testing:
    max_users: 500
    duration: "10m"

# Security Testing
SECURITY_TESTING:
  vulnerability_scanning: true
  dependency_checking: true
  code_analysis: true
  penetration_testing: true
  ssl_certificate_check: true

# Test Data
TEST_DATA:
  fixtures: true
  seed_data: true
  mock_services: true
  test_database: true
  isolated_environments: true

# Test Automation
TEST_AUTOMATION:
  ci_cd_integration: true
  scheduled_tests: true
  parallel_execution: true
  test_reporting: true
  failure_notifications: true

# Quality Gates
QUALITY_GATES:
  test_pass_rate: 95%
  coverage_threshold: 80%
  performance_threshold: 90%
  security_score: 90%
  accessibility_score: 90%
